---

- hosts: all,localhost
  become: true
  roles:
    - { role: wormhole, tags: wormhole }
    - { role: users, tags: users}
    - { role: zerotier, tags: zerotier }
    - { role: nginx, tags: nginx }

