---

- hosts: all,localhost
  become: true
  roles:
    - { role: utils, tags: utils }
    - { role: nodejs, tags: nodejs }
    - { role: users, tags: users }
    - { role: docker, tags: docker }
    - { role: awscli, tags: awscli }