---
- name: Install utility system packages
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
      - jq
      - ruby
      - nodejs
      - npm

- name: Set permissions on global node_modules
  file:
    path: /usr/local/lib/node_modules
    state: directory
    mode: '0777'
