- name: Install required system packages
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - amazon-ecr-credential-helper

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce

- name: Start docker
  service:
    name: docker
    state: started

- name: Add ubuntu user to docker group
  user:
    append: yes
    groups: docker
    user: "{{ item }}"
  loop:
    - ubuntu
    - "{{ github_user }}"
